from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    signup_view, 
    login_view, 
    dashboard_view, 
    leaderboard_view, 
    profile_view, 
    admin_dashboard_view, 
    edit_user_view,
    view_profile_view,
    reaction_test_view,
    save_score_view,
    reaction_test_result_view,
    evade_and_sequence_view,
    evade_and_sequence_warning_view,
    save_evade_and_sequence_score_view,
    evade_and_sequence_result_view,
    auto_login_view,
    manage_devices_view,
    delete_user_view,
    evade_and_sequence_instructions_view,
    get_online_status_api,
    debug_online_status_view,
)

urlpatterns = [
    path('', auto_login_view, name='auto_login'),
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('leaderboard/', leaderboard_view, name='leaderboard'),
    path('profile/', profile_view, name='profile'),
    path('admin-dashboard/', admin_dashboard_view, name='admin_dashboard'),
    path('edit-user/<int:user_id>/', edit_user_view, name='edit_user'),
    path('view-profile/<int:user_id>/', view_profile_view, name='view_profile'),
    path('delete-user/<int:user_id>/', delete_user_view, name='delete_user'),
    path('reaction-test/', reaction_test_view, name='reaction_test'),
    path('save-score/', save_score_view, name='save_score'),
    path('reaction-test-result/', reaction_test_result_view, name='reaction_test_result'),
    path('evade-and-sequence-warning/', evade_and_sequence_warning_view, name='evade_and_sequence_warning'),
    path('evade-and-sequence-instructions/', evade_and_sequence_instructions_view, name='evade_and_sequence_instructions'),
    path('evade-and-sequence/', evade_and_sequence_view, name='evade_and_sequence'),
    path('save-evade-and-sequence-score/', save_evade_and_sequence_score_view, name='save_evade_and_sequence_score'),
    path('evade-and-sequence-result/<int:result_id>/', evade_and_sequence_result_view, name='evade_and_sequence_result'),
    path('manage-devices/', manage_devices_view, name='manage_devices'),
    path('api/online-status/', get_online_status_api, name='get_online_status_api'),
    path('api/debug-online-status/', debug_online_status_view, name='debug_online_status'),
    path('logout/', LogoutView.as_view(), name='logout'),
] 