# Generated by Django 4.2.23 on 2025-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactiontestresult',
            name='is_for_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
