# Generated by Django 4.2.23 on 2025-06-21 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_evadeandsequenceresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evadeandsequenceresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='reactiontestresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='evadeandsequenceresult',
            name='is_for_leaderboard',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reactiontestresult',
            name='is_for_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('browser_info', models.TextField(blank=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
    ]
