# Generated by Django 4.2.23 on 2025-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_evadeandsequenceresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evadeandsequenceresult',
            name='misses',
            field=models.IntegerField(default=0),
        ),
    ]
