# Generated by Django 5.2.4 on 2025-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useronlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactiontestresult',
            name='ranked_attempt_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
